apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.metadata.labels.app }}-configmap
  labels:
    app: {{ .Values.metadata.labels.app }}
data: 
  RETAIL_CHECKOUT_PERSISTENCE_PROVIDER: redis
  RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL: redis://{{ .Values.metadata.labels.app }}-redis-service:6379 
  RETAIL_CHECKOUT_ENDPOINTS_ORDERS: http://{{ .Values.metadata.labels.app }}-service:80 